conda:
  auto_init: true
  auto_install: true
  prefix: /usr/local/Caskroom/miniconda/base

dependency_resolvers:
  - type: conda
    auto_init: true
    auto_install: true
    conda_exec: /usr/local/bin/conda
