name: Setup Galaxy Environment

on:
  push:
    branches:
      - main
  schedule:
    # Also runs at noon on the seventh day of every month
    - cron: '12 0 7 * *'

jobs:
  setup:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Install Galaxy, dependencies, and verify they are installed successfully (including starting Galaxy)
        run: |
          ./setup.sh

