name: Setup Galaxy Environment

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            /path/to/galaxy/.venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Galaxy and dependencies on macOS
        run: bash setup.sh

